version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "12:00"
      ignore:
          - dependency-name: "@types/node"
      commit-message:
          prefix: ""
          prefix-development: "[NPM]"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
      schedule:
          interval: weekly
          day: monday
          time: "12:00"
      commit-message:
          prefix: "[DEP]"
