version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "*"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "[DEP]"
    open-pull-requests-limit: 10

  # Update Node dependencies
  - package-ecosystem: "npm"
    directories:
      - "*"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
    labels:
      - dependencies
      - node
    ignore:
      - dependency-name: "@types/node"
    commit-message:
      prefix: "[NPM]"
    open-pull-requests-limit: 10

  # Update Python dependencies
  - package-ecosystem: "pip"
    directories:
      - "*"
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "[PIP]"
    open-pull-requests-limit: 10
